[project]
name = "mdstats"
version = "1.0.0"
description = "A simple command line tool to get statistics of markdown files."
readme = "README.md"
authors = [
    { name = "brainthra", email = "96686520+brainthra@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
mdstats = "mdstats.cli:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "ruff>=0.16.2",
]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
]

[tool.pyright]
pythonVersion = "3.12"
typeCheckingMode = "standard"
